### ISSUE TITLE
Discord link is not working.

### ISSUE THREAD

**Issue by SarveshDevrukhkar** [inkerton/inkerton#1]
# Description
I was trying to connect with you on Discord, so I go to it through your README but that link is giving the expected result.

**Comment by inkerton** [comment]
try it now it should redirect you to my id "janvi2025" . This is my discord id.
I haven't turned my project into opensource but will do it shortly then you could also join the server.

**Comment by SAD0XER** [comment]
> try it now it should redirect you to my id "janvi2025" . This is my discord id. I haven't turned my project into opensource but will do it shortly then you could also join the server.

I think you have mentioned your id as 'janvi......' Like this.
